# Generated by Django 3.1.4 on 2020-12-21 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='دامنه')),
                ('description', models.TextField(verbose_name='شرح')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='تصویر')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار محصول')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'موجود'), ('d', 'نا موجود'), ('f', 'بزودی')], max_length=1)),
            ],
        ),
    ]
