# Generated by Django 3.1.4 on 2020-12-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20201223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default=None, to='eshop.Category', verbose_name='دسته ها'),
        ),
    ]
