# Generated by Django 3.1.4 on 2020-12-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20201223_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='barand',
            field=models.BooleanField(default=False, verbose_name='آیا این دسته نام برند است ؟'),
        ),
    ]
