# Generated by Django 3.1.4 on 2021-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری ها'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='title',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
    ]
