# Generated by Django 3.1.4 on 2021-01-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_auto_20210111_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='ContactUs',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'اطلاع', 'verbose_name_plural': 'اطلاعات'},
        ),
    ]
