# Generated by Django 3.1.4 on 2021-02-03 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0015_auto_20210203_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewer',
        ),
        migrations.AddField(
            model_name='product',
            name='viewer',
            field=models.ManyToManyField(null=True, related_name='viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
