# Generated by Django 3.1.4 on 2021-02-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_auto_20210203_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewer',
        ),
    ]
