# Generated by Django 3.1.4 on 2021-02-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AlterModelOptions(
            name='order_detail',
            options={'verbose_name': 'جزییات سبد', 'verbose_name_plural': 'جزییات سبد ها'},
        ),
    ]
